/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.wadhams.image.renamer.util

import com.wadhams.image.renamer.app.MainApp

import static groovy.io.FileType.FILES

class ImageFinder {
	List<File> findImages(String fileExtension) {
		List<File> fileList = []
		
		File baseDir = new File('.')
		baseDir.eachFileRecurse(FILES) {f ->
			if (f.name.startsWith('IMG_') && f.name.endsWith(fileExtension.toUpperCase())) {
				fileList << f
			}
		}
		return fileList
	}
}
