/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.wadhams.image.renamer.util

import com.wadhams.image.renamer.app.MainApp
import com.wadhams.image.renamer.type.FileExtension

import static groovy.io.FileType.FILES

import java.util.regex.Pattern

class ImageFinder {
	Pattern extensionPattern = ~/.*\.(\w{3,4})$/
	Pattern datedFilenamePattern = ~/\d{8}_\d{6}.*/
	
	List<File> findImages(FileExtension fileExtension) {
		List<File> fileList = []
		
		File baseDir = new File('.')
		println "baseDir: ${baseDir.getAbsolutePath()}"
		baseDir.eachFileRecurse(FILES) {f ->
			String extension = ''
			def m = f.name =~ extensionPattern
			if (m) {
				//println m[0]
				//println m[0][1]
				extension = m[0][1]
			}
	
			if (f.name.startsWith('IMG_') && FileExtension.findByExtension(extension) == fileExtension) {
				fileList << f
			}
		}
		println "${fileList.size()} $fileExtension files found."
		println ''
		
		return fileList
	}
	
	String findOldestImageFilename() {
		File baseDir = new File('C:\\Grey_Nomad_Media\\Image_Files')	//BAD!!!
		String oldestImageFilename = ''
		File oldestImageFile
		baseDir.eachFileRecurse(FILES) {f ->
			def m = f.name =~ datedFilenamePattern
			if (m) {
				//println m[0]
				if (f.name > oldestImageFilename) {
					oldestImageFilename = f.name
					oldestImageFile = f
				}
			}
		}
		return oldestImageFile.getAbsolutePath()
	}
}
