/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.wadhams.image.renamer

import com.wadhams.image.renamer.app.MainApp

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new MainApp()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
